### ISSUE TITLE
analytics.page() is always a route behind

### ISSUE THREAD

**Issue by stevenhornung** [percolatestudio/meteor-segment.io#13]
If I call analytics.page() in Router.onRun, it will always report the previously visited path.  For example, if I go directly to /home it reports path as /home.  If I then navigate to say /about, it again reports /home.  If I navigate to another page it will report /about.  

If I continue this, it will always send off the path/title/url/etc as the path before.  This is a problem because I can never see the last route visit before a user exits the site.

**Comment by fongandrew** [comment]
Also running into this issue. Best guess as to what's going on is that analytics.js is checking `window.location` for the path and Iron Router doesn't update that until after the `Router.onRun` hook is complete.

Fortunately, we can extract the correct (current) path from the controller object calling the `Router.onRun` hook and pass to `analytics.page()`. Here's my quick workaround:

```javascript
Router.onRun(function() {
  var state = this.location && this.location.get();
  if (state) {
    var path = state.path;
    var origin = state.origin;

    // Origin is missing from all but initial call in client, so check 
    // window.location in client code
    if (!origin && Meteor.isClient) {
      origin = window.location.origin || 
              (window.location.protocol + "//" + window.location.host);
    }
    
    analytics.page({
      path: path,
      url: origin + path
    });
  } else {
    analytics.page();
  }
  this.next();
});
```

**Comment by themeteorchef** [comment]
@fongandrew thanks for this! Can confirm this works really well and also seems to prevent multiple page views being tracked. Just calling `analytics.page()` from within `Router.onRun()` was causing the function to fire 1-3 times per route.

@percolatestudio this (or something close to it) would be nice to see baked into the package/docs.

**Comment by coopermaruyama** [comment]
@fongandrew thanks, worked for me too.

**Comment by stevenhornung** [comment]
@fongandrew this works great! thanks

**Comment by bramsdenteuling** [comment]
I also have this issue. The solution of @fongandrew is not working, somehow state.path gives back only the root path ('/').

**Comment by delemach** [comment]
@bramsdenteuling you probably solved it by now, but I suggest getting `path` from the `window.location` as well. Otherwise `path` will still be the path from the past route, not the current route, which may be what you're seeing. So:

```
path = window.location.pathname; //note it's pathname not path 
```

**Comment by lorensr** [comment]
Readme simple `onRun` doesn't work for me, even after moving to `onAfterAction`. Using fongandrew's suggestion, with added name param and `title`:
```
    analytics.page @route.getName(),
      title: @route.getName()
      ...
```
(https://segment.com/docs/libraries/analytics.js/#page)
Results in:
```
{
  name: 'notification-settings'
  title: 'notification-settings'
  url: 'http://localhost:3000/settings/notifications?q=a'
  path: /settings/notifications
  referrer: ''
  search: '?q=a'
}
```

Only caveat is if you want the hash, use `this.location.get().href` instead of `origin + path`

**Comment by zol** [comment]
An easier (and hacky) workaround to this issue is to defer the `analytics.page()` call to the next tick knowing that sometime later in the current tick it will be correct, so do:

```
Meteor.setTimeout(function() {
  analytics.page();
});
```

I'll update the readme accordingly. Thanks all.
