### ISSUE TITLE
analytics.min.js not found 

### ISSUE THREAD

**Issue by almogdesign** [percolatestudio/meteor-segment.io#15]
I'm getting the following error 

 http://cdn.segment.com/analytics.js/v1/3CPgESobOgOkpNB/analytics.min.js 404 (Not Found)

**Comment by lambtron** [comment]
Hey @almogdesign, can you confirm that the `writeKey` that you are providing is correct?

Looks like the 404 is because the `writeKey` is incorrect. When we try an actual `writeKey`, the script returns successfully.

**Comment by almogdesign** [comment]
Yes correct write key it looks like it's failing here 

// Insert our script next to the first script element.
  var first = document.getElementsByTagName('script')[0];
  first.parentNode.insertBefore(script, first);

Here is the full error 

GET http://cdn.segment.com/analytics.js/v1/3CPgESobOgOkpNB/analytics.min.js snippet.js:74 analytics.loadsegment_io.js?ac41c2169a6e58637fec9aab5a8db3fc23b4b6bb:10 (anonymous function)dynamics_browser.js:51 Meteor.bindEnvironmentlivedata_connection.js:388 _.extend._maybeInvokeCallbacklivedata_connection.js:408 _.extend.receiveResultlivedata_connection.js:1461 _.extend._livedata_resultlivedata_connection.js:253 onMessagestream_client_sockjs.js:172 (anonymous function)underscore.js:105 _.each._.forEachstream_client_sockjs.js:171 _.extend._launchConnection.self.socket.onmessagesockjs-0.3.4.js:87 REventTarget.dispatchEventsockjs-0.3.4.js:1072 SockJS._dispatchMessagesockjs-0.3.4.js:1130 SockJS._didMessagesockjs-0.3.4.js:1277 SockJS.websocket.that.ws.onmessage

**Comment by almogdesign** [comment]
Yes this was an issue on my end with the tracking code

**Comment by akinnee** [comment]
Had this issue. My installed URL wasn't exactly right. I had to add the port.
