### ISSUE TITLE
My page events are not being tracked

### ISSUE THREAD

**Issue by orlaqp** [percolatestudio/meteor-segment.io#16]
I just sign up with segment.io and while testing the different features I noticed that the analytics.page() method under Router.onRun is not really working. it only track the page when opening the for the first time. Every other page changes are not tracked.

One thing I noticed while I was checking why this was happening is that it you put a `debugger` statement like this:

```coffeescript
Router.onRun ->
    debugger
    analytics.page()
    @next()
```

and go through the code, it does work correctly, maybe some kind of timing issue? Not sure and at this point do not know how to fix but I wanted to share this detail. Hopefully somebody else can see something here that I do not.

Thanks!

**Comment by chanpory** [comment]
I also cannot get this to work. Calling analytics.page() anywhere does not register the pageLoad event.

**Comment by chanpory** [comment]
@orlaqp 

After some digging it looks this issue could be related to configuration settings within Segment.io. If you go to your dashboard, then in the Mixpanel advanced options. You'll see options for page level tracking.

In my case, I had "Track Named Pages to Mixpanel" checked on, but "Track All Pages to Mixpanel" turned off. If I do, analytics.page("test"). I was able to see the event in Mixpanel.

![screen shot 2015-02-26 at 10 08 30 am](https://cloud.githubusercontent.com/assets/350561/6398310/957523ac-bd9f-11e4-82ae-5b0b6f8f8a27.png)

**Comment by orlaqp** [comment]
Thanks for your comment @chanpory but I am using google analytics integration not mixpanel in any case Now it is working a little better because is tracking the pages but always one page behind. Example:

Let's say I have page1, page2 and page3 and I am in page1. When I click page2 i see an entry for page1 in segment.io debugger, when I click page 3 I see an entry for page2 .. etc

**Comment by orlaqp** [comment]
My original issue is not heppenning anymore now I have this one:

https://github.com/percolatestudio/meteor-segment.io/issues/13
