### ISSUE TITLE
Not accessible on server

### ISSUE THREAD

**Issue by themeteorchef** [percolatestudio/meteor-segment.io#17]
It looks like this was supposed to be fixed in #4 but the error still persists.

If I attempt to define `analytics.load(myKey)` anywhere in the `/server` directory, I get the following:

![error](http://cl.ly/image/202M143j0P3f/Image%202015-02-28%20at%201.48.28%20PM.png)

Tried a few experiments to no avail:
- Move code out of `Meteor.startup()` and into its own file.
- Attempt to make file calling `analytics.load()` load last.
- Wrap call to `analytics.load()` in a `setTimeout()`.

Doesn't appear to be relevant, but there seems to be a typo [here](https://github.com/percolatestudio/meteor-segment.io/blob/master/server.js#L4). Seems like `writeKet` should be `writeKey`.

Let me know if you need any more information :)

**Comment by rhyslbw** [comment]
Sounds like your running 3.0.0:

> Note: We've switched to the official versioning scheme for tracking upstream packages (1.1.0_1). Unfortunately, meteor will pick the highest version (in this case 3.0.0) which is old and should not be used. Please choose the latest 1.x version explicitly). *

`meteor add percolatestudio:segment.io@1.1.1_1` should sort it out

**Comment by themeteorchef** [comment]
:+1:
