### ISSUE TITLE
Alias overwriting existing profile in mixpanel

### ISSUE THREAD

**Issue by dapearce** [percolatestudio/meteor-segment.io#19]
I'm using this with Mixpanel and calling `analytics.alias()` only once, in the callback of `Accounts.createUser`, right before `analytics.identify()`. The issue I'm running into, is if I log out and create a new account, it aliases to the old account and overwrites everything.

In some situations, it's very common to have multiple accounts. Is there a way to avoid this? For example only aliasing once per profile.

To clarify more: If I'm using 1 computer, and I create 3 different accounts, it will always update the same profile in Mixpanel for each account, rather than creating a new profile. Even overwriting the "id" field with the new id. So I have 3 accounts in my database, but only 1 user in Mixpanel.

**Comment by zol** [comment]
@dapearce This sounds like a question for the segment team. This package simply allows you to easily add it to a Meteor app.
