### ISSUE TITLE
Uncaught TypeError: analytics.initialize is not a function 

### ISSUE THREAD

**Issue by sferoze** [percolatestudio/meteor-segment.io#32]
I cannot get this package to work. 

I made sure to add `meteor add percolatestudio:segment.io@2.0.0_1`

and I have put 

```
analytics.load('MY_KEY')
```

in a javascript file on the client. 

And I get this error in the console:

```
Uncaught TypeError: analytics.initialize is not a function(anonymous function) @ okgrow_analytics.js?9544bb268e826ca356545705e973f9e8a13d3aa0:19runStartupCallbacks @ startup_client.js:30ready @ startup_client.js:32
```

**Comment by sferoze** [comment]
It seems like the analytics is working, but in the client I keep getting the error

`Uncaught TypeError: analytics.initialize is not a function`

**Comment by zol** [comment]
I see okgrow_analytics in the stack trace, which indicates the error is coming form a different package.
