### ISSUE TITLE
Not sending when calling analytics.page() in onRun()

### ISSUE THREAD

**Issue by RXminuS** [percolatestudio/meteor-segment.io#8]
If I look in my segment.io debugger window the analytics.page() event never arrives unless I call analytics.page() from my Chrome console after the page has loaded. I suspect that the analytics.js script simply hasn't loaded yet and the analytics.page() isn't run reactively dependant on the successful loading.

**Comment by orlaqp** [comment]
Hi @RXminuS same thing is happening to me. I just sign up with segment.io and started to to test it and I having exactly the same issue. by the way i am using this package: 

https://github.com/percolatestudio/meteor-segment.io

One thing I noticed while I was checking why this was happening is that it you put a `debugger` statement like this:

```coffeescript
Router.onRun ->
    debugger
    analytics.page()
    @next()
```

and go through the code, it does work correctly, maybe some kind of timing issue? Not sure and at this point do not know how to fix but I wanted to share this detail. Hopefully somebody else can see something here that I do not.

Thanks!

**Comment by dapearce** [comment]
This is also happening with me, I'm using flow router triggers, but same thing -- it works on initial load, but doesn't send again. I can send from the Chrome console, and if I log anything before/after it shows up, but the event never makes it to segments debugger.
